SELECT ?var1  ?var2  ?var2Label  ?var3  ?var4Label  ?var5Label 
WHERE {
  ?var2  <http://www.wikidata.org/prop/direct/P776>  ?var1 .
  ?var2  <http://www.wikidata.org/prop/P625>  ?var6 .
  ?var6  <http://www.wikidata.org/prop/statement/P625>  ?var3 .
 OPTIONAL {
  ?var6  <http://www.w3.org/ns/prov#wasDerivedFrom>  ?var7 .
  ?var7  <http://www.wikidata.org/prop/reference/P143>  ?var4 .
  ?var7  <http://www.wikidata.org/prop/reference/P248>  ?var5 .
 }
 {
  SELECT( COUNT ( ?var2  ) AS  ?var8  ) ?var1 
  WHERE   {
    ?var2  <http://www.wikidata.org/prop/direct/P776>  ?var1 .
    ?var2  <http://www.wikidata.org/prop/direct/P625>  ?var3 .
  }
  GROUP BY  ?var1 
 HAVING    ( (  ?var8  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) ) 
  }
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "sv".
  }
}
ORDER BY ASC( ?var1 )


----<>>> Kommt (?) fast in allen Dataframes vor.
Danach suchen?
