SELECT ?var1  ?var1Label  ?var2 
WHERE {
  ?var1  <http://www.wikidata.org/prop/P39>  ?var3 .
  ?var3  <http://www.wikidata.org/prop/statement/P39>  <http://www.wikidata.org/entity/Q19546> .
  ?var3  <http://www.wikidata.org/prop/qualifier/p580>  ?var2 .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en".
  }
}
ORDER BY ASC( ?var2 )
