SELECT ?var1  ?var1Label  ?var2  ?var3  ?var4 
WHERE {
 {
   ?var1  <http://www.wikidata.org/prop/direct/P119>  <http://www.wikidata.org/entity/Q252312> .
  {
    ?var1  <http://www.wikidata.org/prop/P119>  ?var5 .
  }
  {
    ?var5  <http://www.wikidata.org/prop/qualifier/P965>  ?var3 .
  }
   MINUS    {
     ?var5  <http://www.wikidata.org/prop/qualifier/P625>  ?var4 .
   }
 }
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en",  "sv".
  }
}
ORDER BY ASC( ?var1Label )

SELECT( COUNT ( DISTINCT  ?var1  ) AS  ?var2  )
WHERE {
  <http://www.bigdata.com/queryHints#Query>  <http://www.bigdata.com/queryHints#optimizer>  "None".
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q6256> .
 {
  {
   {
     ?var1  <http://www.wikidata.org/prop/direct/P530>  ?var3 .
     ?var1  <http://www.wikidata.org/prop/P530>  ?var4 .
    {
     {
       ?var4  <http://www.wikidata.org/prop/qualifier/P805>  <http://www.wikidata.org/entity/Q4825537> .
     }
    }
   }
  }
 }
 {
  {
   {
     ?var1  <http://www.wikidata.org/prop/direct/P47>  <http://www.wikidata.org/entity/Q183> .
   }
  }
 }
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en".
  }
}
LIMIT 50
