SELECT ?var1  ?var2  ?var3 
WHERE {
  <http://www.wikidata.org/entity/P2002>  <http://wikiba.se/ontology#claim>  ?var4 ;
 <http://wikiba.se/ontology#statementProperty>  ?var5 ;
 <http://wikiba.se/ontology#qualifier>  ?var6 ;
 <http://wikiba.se/ontology#reference>  ?var7 .
 {
   BIND (  "mainsnak" AS  ?var3 ).
   ?var1  ?var4  [  ?var5  ?var2  ] .
 }
  UNION
 {
   BIND (  "qualifier" AS  ?var3 ).
   ?var1  ?var8  [  ?var6  ?var2  ] .
 }
  UNION
 {
   BIND (  "reference" AS  ?var3 ).
   ?var1  ?var8  [  <http://www.w3.org/ns/prov#wasDerivedFrom>  [  ?var7  ?var2  ]  ] .
 }
}
ORDER BY ASC( ?var3 )ASC( ?var2 )
