SELECT DISTINCT ?var1  ?var1Label  ?var2  ?var2Label 
WHERE {
  ?var2 ( <http://www.wikidata.org/prop/P22> | <http://www.wikidata.org/prop/P25> ) [ ( <http://www.wikidata.org/prop/statement/P22> | <http://www.wikidata.org/prop/statement/P25> ) ?var1 ;
( <http://www.w3.org/ns/prov#wasDerivedFrom> / <http://www.wikidata.org/prop/reference/P248> /( <http://www.wikidata.org/prop/direct/P361> | <http://www.wikidata.org/prop/direct/P179> )+) <http://www.wikidata.org/entity/Q83367>  ] .
 FILTER (  (  NOT EXISTS  {
   ?var1  <http://www.wikidata.org/prop/P40>  [  <http://www.wikidata.org/prop/statement/P40>  ?var2 ;
( <http://www.w3.org/ns/prov#wasDerivedFrom> / <http://www.wikidata.org/prop/reference/P248> /( <http://www.wikidata.org/prop/direct/P361> | <http://www.wikidata.org/prop/direct/P179> )+) <http://www.wikidata.org/entity/Q83367>  ] .
 }
 ) 
) .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "he".
  }
}

Detected a difference between the number of detected scenarios and found metadata in the query.
one:  0 two:  0 three:  0 4:  0 5:  0 6:  0 7:  0 8:  0 9:  0 10:  0 11:  0 12:  0 
 bind:  0 blank:  1 filter:  1 group:  0 literal:  0 
 minus:  0 optional:  0 prop_path:  1 subselect:  0 union:  0 values:  0 service:  0 other:  0
2
data/2017-07-10_2017-08-06/organic/reference_metadata/derived_+_reference_property/22801 2017-07-13 00:47:04.json
