Detected a difference between the number of detected scenarios and found metadata in the query.
one:  0 two:  0 three:  0 4:  0 5:  0 6:  0 7:  0 8:  0 9:  0 10:  0 11:  0 12:  0 
 bind:  0 blank:  1 filter:  0 group:  0 literal:  0 
 minus:  0 optional:  0 prop_path:  1 subselect:  0 union:  2 values:  0 service:  0 other:  0
3
data/2017-07-10_2017-08-06/organic/reference_metadata/derived_+_reference_property/51551 2017-07-17 22:22:08.json

SELECT ?var1  ?var1Label  ?var2  ?var2Label 
WHERE {
  ?var3  <http://www.wikidata.org/prop/P40>  [  <http://www.wikidata.org/prop/statement/P40>  ?var4 ;
( <http://www.w3.org/ns/prov#wasDerivedFrom> / <http://www.wikidata.org/prop/reference/P248> /( <http://www.wikidata.org/prop/direct/P361> | <http://www.wikidata.org/prop/direct/P179> )+) <http://www.wikidata.org/entity/Q83367>  ] .
 {
   ?var3  <http://www.wikidata.org/prop/P460>  [  <http://www.wikidata.org/prop/statement/P460>  ?var1 ;
( <http://www.w3.org/ns/prov#wasDerivedFrom> / <http://www.wikidata.org/prop/reference/P248> / <http://www.wikidata.org/prop/direct/P50> ) <http://www.wikidata.org/entity/Q26456>  ] .
   ?var3  <http://wikiba.se/ontology#sitelinks>  ?var5 .
   ?var1  <http://wikiba.se/ontology#sitelinks>  ?var6 .
 FILTER (   ( (  ?var5  >  ?var6  ) ) 
) .
 }
  UNION
 {
   BIND (  ?var3  AS  ?var1 ).
 FILTER (   (  NOT EXISTS   {
    ?var3  <http://www.wikidata.org/prop/P460>  [  <http://www.wikidata.org/prop/statement/P460>  [] ;
( <http://www.w3.org/ns/prov#wasDerivedFrom> / <http://www.wikidata.org/prop/reference/P248> / <http://www.wikidata.org/prop/direct/P50> ) <http://www.wikidata.org/entity/Q26456>  ] .
  }
 ) 
) .
 }
  ?var4  <https://query.wikidata.org/bigdata/namespace/wdq/foo> ? ?var2 .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "he".
  }
}
